"""
Patient RAG Advisor
--------------------
A FastAPI service that lets a patient upload a document (lab report, discharge
summary, prescription notes, etc.), stores it in a local vector database, and
answers questions using a locally-running Ollama model, grounded only in the
uploaded content.

IMPORTANT: This tool provides general informational guidance only. It is not
a diagnosis and does not replace a licensed medical professional. See the
disclaimer baked into every response.
"""

import os
import shutil
import uuid
from pathlib import Path
from typing import List

from fastapi import FastAPI, File, UploadFile, Form, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from rag_engine import RAGEngine

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
UPLOAD_DIR = Path("uploads")
UPLOAD_DIR.mkdir(exist_ok=True)

OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
OLLAMA_LLM_MODEL = os.getenv("OLLAMA_LLM_MODEL", "llama3.1")
OLLAMA_EMBED_MODEL = os.getenv("OLLAMA_EMBED_MODEL", "nomic-embed-text")
CHROMA_DIR = os.getenv("CHROMA_DIR", "chroma_db")

ALLOWED_EXTENSIONS = {".pdf", ".txt", ".md", ".docx"}

MEDICAL_DISCLAIMER = (
    "This is general information based only on the document you provided, "
    "generated by an AI model and not a medical professional. It is not a "
    "diagnosis or a prescription. Please confirm any decisions with a "
    "licensed doctor or pharmacist, and seek urgent in-person or emergency "
    "care for severe, worsening, or emergency symptoms."
)

app = FastAPI(
    title="Patient RAG Advisor",
    description="Upload a patient document and ask grounded questions about it via a local Ollama model.",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # tighten this in production
    allow_methods=["*"],
    allow_headers=["*"],
)

engine = RAGEngine(
    ollama_base_url=OLLAMA_BASE_URL,
    llm_model=OLLAMA_LLM_MODEL,
    embed_model=OLLAMA_EMBED_MODEL,
    chroma_dir=CHROMA_DIR,
)


# ---------------------------------------------------------------------------
# Schemas
# ---------------------------------------------------------------------------
class AskRequest(BaseModel):
    patient_id: str
    question: str
    top_k: int = 4


class AskResponse(BaseModel):
    answer: str
    sources: List[str]
    disclaimer: str = MEDICAL_DISCLAIMER


class UploadResponse(BaseModel):
    patient_id: str
    filename: str
    chunks_indexed: int
    message: str


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------
@app.get("/health")
def health():
    return {"status": "ok", "ollama_url": OLLAMA_BASE_URL, "llm_model": OLLAMA_LLM_MODEL}


@app.post("/upload", response_model=UploadResponse)
async def upload_document(
    file: UploadFile = File(...),
    patient_id: str = Form(default=None),
):
    """
    Upload a patient document (PDF, TXT, MD, DOCX). It is chunked, embedded
    with the Ollama embedding model, and stored in a per-patient collection
    in ChromaDB so later questions are answered only from this content.
    """
    ext = Path(file.filename).suffix.lower()
    if ext not in ALLOWED_EXTENSIONS:
        raise HTTPException(
            status_code=400,
            detail=f"Unsupported file type '{ext}'. Allowed: {sorted(ALLOWED_EXTENSIONS)}",
        )

    patient_id = patient_id or str(uuid.uuid4())

    dest_path = UPLOAD_DIR / f"{patient_id}_{file.filename}"
    with dest_path.open("wb") as f:
        shutil.copyfileobj(file.file, f)

    try:
        num_chunks = engine.ingest_file(dest_path, patient_id=patient_id)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to process file: {e}")

    return UploadResponse(
        patient_id=patient_id,
        filename=file.filename,
        chunks_indexed=num_chunks,
        message="Document indexed. You can now ask questions using this patient_id.",
    )


@app.post("/ask", response_model=AskResponse)
def ask(req: AskRequest):
    """
    Ask a question about a previously uploaded document. The model is
    instructed to answer ONLY from retrieved context and to recommend
    professional care where appropriate.
    """
    if not engine.has_documents(req.patient_id):
        raise HTTPException(
            status_code=404,
            detail="No documents found for this patient_id. Upload a document first via /upload.",
        )

    result = engine.answer_question(
        patient_id=req.patient_id,
        question=req.question,
        top_k=req.top_k,
    )

    return AskResponse(
        answer=result["answer"],
        sources=result["sources"],
    )


@app.delete("/patient/{patient_id}")
def delete_patient_data(patient_id: str):
    """Remove all indexed data for a patient (privacy / cleanup)."""
    deleted = engine.delete_patient(patient_id)
    if not deleted:
        raise HTTPException(status_code=404, detail="No data found for this patient_id.")
    return {"message": f"All data for patient_id '{patient_id}' deleted."}


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
